import type { Metadata } from "next";
import { Geist, Geist_Mono, Delius_Unicase, Sour_Gummy } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const deliusUnicase = Delius_Unicase({
  variable: "--font-delius-unicase",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const sourGummy = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${deliusUnicase.variable} ${sourGummy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
